### ISSUE TITLE
Query params are repeated in search paging links

### ISSUE THREAD

**Issue by AsgerPetersen** [Dataforsyningen/skraafoto_stac_public#2]
To recreate:

1. Go to `/search` endpoint
2. In the result json follow the link rel `next` (is something like http://localhost:8081/search?token=None?limit=10&pt=PmR0OjIwMjEtMTEtMjIgMTA6MDM6MzUrMDA6MDB-czoyMDIxXzgyXzIwXzVfMDAwMV8wMDAwNTM1NA%3D%3D)
3. Check the link rel `next` in the returned result. It is now something like http://localhost:8081/search?token=None%3Flimit%3D10?token=None%3Flimit%3D10&pt=PGR0OjIwMjEtMTEtMjIgMTA6MDM6MjkrMDA6MDB-czoyMDIxXzgyXzIwXzFfMDAwMV8wMDAwNTM1Mw%3D%3D&limit=10

Notice that `token` and `limit` params are duplicated and we have two `?`.

It doesnt seem to be an issue with paging in `items`.

**Comment by Aramos93** [comment]
fixed in 0998dc17e65d6988b2b3eda3040f59ecb54f33d7
