### ISSUE TITLE
Incorrect values in query parameter `crs`, `bbox-crs`, and`filter-crs` does not give error message

### ISSUE THREAD

**Issue by Nobralyra** [Dataforsyningen/skraafoto_stac_public#22]
Incorrect values in query parameter `crs`, `bbox-crs`, and `filter-crs` in openapi docs GET `/search` does not give error message, but returns the same json response, as if the query parameters `crs`, `bbox-crs`, and `filter-crs` never was given values.

Calls:
`https://api.dataforsyningen.dk/skraafotoapi_test/search?crs=e&limit=10&token=`
`https://api.dataforsyningen.dk/skraafotoapi_test/search?limit=10&bbox-crs=e&token=`
`https://api.dataforsyningen.dk/skraafotoapi_test/search?limit=10&filter-crs=e&token=`

Expected outcome:
Client get returned an error message.

Actual outcome:
Client get the same response json seen in `https://api.dataforsyningen.dk/skraafotoapi_test/search?limit=10&token=`

**Comment by Nobralyra** [comment]
Behaviour in others query parameter:
### ids
_Given value_: d
_Outcome_
`{
  "type": "FeatureCollection",
  "features": [],
  "links": [
    {
      "rel": "self",
      "type": "application/geo+json",
      "href": "http://load201.kmsext.dk:4444/search?limit=10&ids=d",
      "method": "GET",
      "body": null
    }
  ],
  "context": {
    "returned": 0,
    "limit": 10,
    "matched": 1
  }
}`

### datetime
_Given value_: e
_Outcome_
`{
  "detail": [
    "Invalid parameters provided",
    "1 validation error for STACSearch",
    "datetime",
    "  invalid datetime format (type=value_error.datetime)"
  ]
}`
_Given value_: 2019
_Outcome_
`{
  "detail": "unhandled database error"
}`
_Given value_: 2+019
_Outcome_
`{
  "detail": [
    "Invalid parameters provided",
    "1 validation error for STACSearch",
    "datetime",
    "  invalid datetime format (type=value_error.datetime)"
  ]
}`

**Comment by Aramos93** [comment]
Tilføjet crs validators i 0e6e2dc28116bdc64fb8dcdc81fdb52737b88270 
Returnerer nu fejl 400 på dårligt input
