### ISSUE TITLE
Opklaring af dokumentation

### ISSUE THREAD

**Issue by iamfrank** [Dataforsyningen/skraafoto_stac_public#37]
Kommentarer og spørgsmål til [https://github.com/Dataforsyningen/skraafoto_stac_public/blob/main/dokumentation.md]():

> Bemærk, at en Collection blandt andet indeholder aggregeret spatiel og tidslig udstrækning for Items hørende til denne Collection.

Det er ikke tydeligt, hvor man finder de aggregerede data. Jeg formoder, at det er at læse et sted i det JSON reponse eksempel, man kan folde ud under "details" ovenfor, men det er kun et gæt.

> Foto = metadata om

?

> Hvis token er autoriseret, men ens request har en ugyldig parameter, returneres en JSON fejlmeddelelse.

Mindre sproglig justering: "... men requesten har en ugyldig ..." lyder mere korrekt.

**Tilføjet**

> Denne ressource tager imod et `collectionid`, `itemid`, og en `crs` og returnerer ét STAC item i en bestemt collection, som er et GeoJSON objekt.

Er det en bestemt collection eller det returnerede item, som er et GeoJSON objekt?

> **Bemærk** at APIet har en begrænsning på, hvor lang tid en forespørgsel må tage at udføre.

Er det med vilje, at det ikke fremgår, hvor lang tid det drejer sig om?

**Comment by Nobralyra** [comment]
Fået rettet dokumentationen til. Tak.

https://github.com/Dataforsyningen/skraafoto_stac_public/commit/9c6dba39828792ecac6c42e83e94a60a2a236739
