### ISSUE TITLE
"How to get started" comments

### ISSUE THREAD

**Issue by iamfrank** [Dataforsyningen/skraafoto_stac_public#39]
Jeg har læst `howtogetstarted.md` og har lidt feedback til teksten:

> (Lav en henvisning til den tekst der skal skrives, som beskriver sammenspillet mellem de tre API'er).

Lav henvisning eller slet tekst.
 
> Sammenspillet mellem de tre API'er

De nævnte endpoint URLs ender alle på `_test`. Skal det ændres, når det kommer i produktion?

> Skråfoto Cogtiler oversætter COG-formatet til andre formater for de klienter, der ikke understøtter COG (undersøg hvad det er for nogle formater).

Undersøg formater eller slet tekst

**Comment by Nobralyra** [comment]
Ja alle URL'er skal rettes, når vi går i produktion.

Retteleser: https://github.com/Dataforsyningen/skraafoto_stac_public/commit/eaa40458caeefcbc0e62a1317ac8c4cf0a3b4602
