### ISSUE TITLE
Different matched number if using intersects or filter in POST /search

### ISSUE THREAD

**Issue by seskildsen** [Dataforsyningen/skraafoto_stac_public#46]
In POST `/search`.

If using intersects, POINT geometry, and filter to get a direction, the returned matched value is 12.

POST /search

`{
    "intersects": {
        "type": "Point",
        "coordinates":[
            10.4064,
            55.3951
        ]
    },
    "filter-lang": "cql-json",
    "filter": { 
        "and": [ 
            {"eq": [ { "property": "direction" }, "east" ] }
        ]
    }
}`
![Screenshot from 2022-06-07 10-31-45](https://user-images.githubusercontent.com/48592380/172335027-303a6705-2f1e-4f20-880d-3419b3b10eca.png)

But if using only filter and there specify a intersects and a direction the returned matched is 67.

POST /search
`
{
    "filter-lang": "cql-json",
    "filter": { 
         "intersects": [
            { "property": "geometry" },
            {
                "type": "Point",
                "coordinates": [
                10.4064,
                55.3951
                ]
            }
        ],
        "and": [ 
            {"eq": [ { "property": "direction" }, "east" ] }
        ]
    }
}`
![Screenshot from 2022-06-07 10-32-09](https://user-images.githubusercontent.com/48592380/172335093-b5de96b1-fb70-44ea-a2ad-aafa8a025e72.png)

**Comment by AsgerPetersen** [comment]
These are not valid cql filters. The length of the array of `and`ed items must be at least 2.

However it would be nice if the API returned an error in this case: #47
